"""Initial

Revision ID: 8b85fcfccc5f
Revises:
Create Date: 2024-06-24 04:14:48.104843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b85fcfccc5f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_results_id"), "llm_results", ["id"], unique=False)
    op.create_index(
        op.f("ix_llm_results_model"), "llm_results", ["model"], unique=False
    )
    op.create_index(
        op.f("ix_llm_results_prompt_hash"), "llm_results", ["prompt_hash"], unique=False
    )
    op.create_index(
        op.f("ix_llm_results_status"), "llm_results", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_results_status"), table_name="llm_results")
    op.drop_index(op.f("ix_llm_results_prompt_hash"), table_name="llm_results")
    op.drop_index(op.f("ix_llm_results_model"), table_name="llm_results")
    op.drop_index(op.f("ix_llm_results_id"), table_name="llm_results")
    op.drop_table("llm_results")
    # ### end Alembic commands ###
