name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8
    - name: Set up environment
      run: cp .sample.env .env
    - name: Run linter
      run: flake8 --config=.flake8 .
    - name: Run tests
      run: pytest

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t llm-hub .
    - name: Test Docker image
      run: |
        docker run -d --name llm-hub-container --env-file .sample.env llm-hub
        docker ps | grep -q llm-hub-container
